revoke delete on table "public"."lead_custom_fields" from "anon";

revoke insert on table "public"."lead_custom_fields" from "anon";

revoke references on table "public"."lead_custom_fields" from "anon";

revoke select on table "public"."lead_custom_fields" from "anon";

revoke trigger on table "public"."lead_custom_fields" from "anon";

revoke truncate on table "public"."lead_custom_fields" from "anon";

revoke update on table "public"."lead_custom_fields" from "anon";

revoke delete on table "public"."lead_custom_fields" from "authenticated";

revoke insert on table "public"."lead_custom_fields" from "authenticated";

revoke references on table "public"."lead_custom_fields" from "authenticated";

revoke select on table "public"."lead_custom_fields" from "authenticated";

revoke trigger on table "public"."lead_custom_fields" from "authenticated";

revoke truncate on table "public"."lead_custom_fields" from "authenticated";

revoke update on table "public"."lead_custom_fields" from "authenticated";

revoke delete on table "public"."lead_custom_fields" from "service_role";

revoke insert on table "public"."lead_custom_fields" from "service_role";

revoke references on table "public"."lead_custom_fields" from "service_role";

revoke select on table "public"."lead_custom_fields" from "service_role";

revoke trigger on table "public"."lead_custom_fields" from "service_role";

revoke truncate on table "public"."lead_custom_fields" from "service_role";

revoke update on table "public"."lead_custom_fields" from "service_role";

revoke delete on table "public"."leads" from "anon";

revoke insert on table "public"."leads" from "anon";

revoke references on table "public"."leads" from "anon";

revoke select on table "public"."leads" from "anon";

revoke trigger on table "public"."leads" from "anon";

revoke truncate on table "public"."leads" from "anon";

revoke update on table "public"."leads" from "anon";

revoke delete on table "public"."leads" from "authenticated";

revoke insert on table "public"."leads" from "authenticated";

revoke references on table "public"."leads" from "authenticated";

revoke select on table "public"."leads" from "authenticated";

revoke trigger on table "public"."leads" from "authenticated";

revoke truncate on table "public"."leads" from "authenticated";

revoke update on table "public"."leads" from "authenticated";

revoke delete on table "public"."leads" from "service_role";

revoke insert on table "public"."leads" from "service_role";

revoke references on table "public"."leads" from "service_role";

revoke select on table "public"."leads" from "service_role";

revoke trigger on table "public"."leads" from "service_role";

revoke truncate on table "public"."leads" from "service_role";

revoke update on table "public"."leads" from "service_role";

alter table "public"."lead_custom_fields" drop constraint "lead_custom_fields_custom_field_id_fkey";

alter table "public"."lead_custom_fields" drop constraint "lead_custom_fields_lead_id_fkey";

alter table "public"."leads" drop constraint "leads_profile_id_fkey";

alter table "public"."lead_custom_fields" drop constraint "lead_custom_fields_pkey";

alter table "public"."leads" drop constraint "leads_pkey";

drop index if exists "public"."lead_custom_fields_pkey";

drop index if exists "public"."leads_pkey";

drop table "public"."lead_custom_fields";

drop table "public"."leads";

create table "public"."location_lead_custom_fields" (
    "created_at" timestamp with time zone not null default now(),
    "lead_id" bigint not null,
    "custom_field_id" bigint not null,
    "value" text not null
);


alter table "public"."location_lead_custom_fields" enable row level security;

create table "public"."location_leads" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "creator_id" uuid not null,
    "budget" bigint,
    "status" lead_statuses not null default 'new'::lead_statuses,
    "source" lead_sources not null default 'other'::lead_sources,
    "score" smallint not null default '1'::smallint,
    "custom_fields" jsonb,
    "location_id" bigint not null
);


alter table "public"."location_leads" enable row level security;

CREATE UNIQUE INDEX lead_custom_fields_pkey ON public.location_lead_custom_fields USING btree (lead_id, custom_field_id);

CREATE UNIQUE INDEX leads_pkey ON public.location_leads USING btree (id);

alter table "public"."location_lead_custom_fields" add constraint "lead_custom_fields_pkey" PRIMARY KEY using index "lead_custom_fields_pkey";

alter table "public"."location_leads" add constraint "leads_pkey" PRIMARY KEY using index "leads_pkey";

alter table "public"."location_lead_custom_fields" add constraint "lead_custom_fields_custom_field_id_fkey" FOREIGN KEY (custom_field_id) REFERENCES custom_fields(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."location_lead_custom_fields" validate constraint "lead_custom_fields_custom_field_id_fkey";

alter table "public"."location_lead_custom_fields" add constraint "lead_custom_fields_lead_id_fkey" FOREIGN KEY (lead_id) REFERENCES location_leads(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."location_lead_custom_fields" validate constraint "lead_custom_fields_lead_id_fkey";

alter table "public"."location_leads" add constraint "leads_location_id_fkey" FOREIGN KEY (location_id) REFERENCES locations(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."location_leads" validate constraint "leads_location_id_fkey";

alter table "public"."location_leads" add constraint "leads_profile_id_fkey" FOREIGN KEY (creator_id) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."location_leads" validate constraint "leads_profile_id_fkey";

grant delete on table "public"."location_lead_custom_fields" to "anon";

grant insert on table "public"."location_lead_custom_fields" to "anon";

grant references on table "public"."location_lead_custom_fields" to "anon";

grant select on table "public"."location_lead_custom_fields" to "anon";

grant trigger on table "public"."location_lead_custom_fields" to "anon";

grant truncate on table "public"."location_lead_custom_fields" to "anon";

grant update on table "public"."location_lead_custom_fields" to "anon";

grant delete on table "public"."location_lead_custom_fields" to "authenticated";

grant insert on table "public"."location_lead_custom_fields" to "authenticated";

grant references on table "public"."location_lead_custom_fields" to "authenticated";

grant select on table "public"."location_lead_custom_fields" to "authenticated";

grant trigger on table "public"."location_lead_custom_fields" to "authenticated";

grant truncate on table "public"."location_lead_custom_fields" to "authenticated";

grant update on table "public"."location_lead_custom_fields" to "authenticated";

grant delete on table "public"."location_lead_custom_fields" to "service_role";

grant insert on table "public"."location_lead_custom_fields" to "service_role";

grant references on table "public"."location_lead_custom_fields" to "service_role";

grant select on table "public"."location_lead_custom_fields" to "service_role";

grant trigger on table "public"."location_lead_custom_fields" to "service_role";

grant truncate on table "public"."location_lead_custom_fields" to "service_role";

grant update on table "public"."location_lead_custom_fields" to "service_role";

grant delete on table "public"."location_leads" to "anon";

grant insert on table "public"."location_leads" to "anon";

grant references on table "public"."location_leads" to "anon";

grant select on table "public"."location_leads" to "anon";

grant trigger on table "public"."location_leads" to "anon";

grant truncate on table "public"."location_leads" to "anon";

grant update on table "public"."location_leads" to "anon";

grant delete on table "public"."location_leads" to "authenticated";

grant insert on table "public"."location_leads" to "authenticated";

grant references on table "public"."location_leads" to "authenticated";

grant select on table "public"."location_leads" to "authenticated";

grant trigger on table "public"."location_leads" to "authenticated";

grant truncate on table "public"."location_leads" to "authenticated";

grant update on table "public"."location_leads" to "authenticated";

grant delete on table "public"."location_leads" to "service_role";

grant insert on table "public"."location_leads" to "service_role";

grant references on table "public"."location_leads" to "service_role";

grant select on table "public"."location_leads" to "service_role";

grant trigger on table "public"."location_leads" to "service_role";

grant truncate on table "public"."location_leads" to "service_role";

grant update on table "public"."location_leads" to "service_role";

create policy "Enable all access for creators"
on "public"."location_leads"
as permissive
for all
to authenticated
using ((( SELECT auth.uid() AS uid) = creator_id));


create policy "Enable insert for location employees"
on "public"."location_leads"
as permissive
for insert
to public
with check ((( SELECT auth.uid() AS uid) IN ( SELECT location_profiles.profile_id
   FROM location_profiles
  WHERE (location_profiles.location_id = location_leads.location_id))));


create policy "Enable read access for all users"
on "public"."location_profiles"
as permissive
for select
to authenticated
using (true);


create policy "Enable read access for location profiles"
on "public"."locations"
as permissive
for select
to authenticated
using ((( SELECT auth.uid() AS uid) IN ( SELECT location_profiles.profile_id
   FROM location_profiles
  WHERE (location_profiles.location_id = locations.id))));



