create table "public"."business_appointment_profiles" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "business_id" uuid not null,
    "appointment_id" bigint not null,
    "profile_id" uuid not null
);


alter table "public"."business_appointment_profiles" enable row level security;

create table "public"."business_appointments" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "business_id" uuid not null,
    "location_id" bigint,
    "job_id" bigint,
    "start_datetime" timestamp with time zone not null,
    "end_datetime" timestamp with time zone not null,
    "name" text not null
);


alter table "public"."business_appointments" enable row level security;

CREATE UNIQUE INDEX business_appointment_profiles_pkey ON public.business_appointment_profiles USING btree (id);

CREATE UNIQUE INDEX business_appointments_pkey ON public.business_appointments USING btree (id);

alter table "public"."business_appointment_profiles" add constraint "business_appointment_profiles_pkey" PRIMARY KEY using index "business_appointment_profiles_pkey";

alter table "public"."business_appointments" add constraint "business_appointments_pkey" PRIMARY KEY using index "business_appointments_pkey";

alter table "public"."business_appointment_profiles" add constraint "business_appointment_profiles_appointment_id_fkey" FOREIGN KEY (appointment_id) REFERENCES business_appointments(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."business_appointment_profiles" validate constraint "business_appointment_profiles_appointment_id_fkey";

alter table "public"."business_appointment_profiles" add constraint "business_appointment_profiles_business_id_fkey" FOREIGN KEY (business_id) REFERENCES businesses(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."business_appointment_profiles" validate constraint "business_appointment_profiles_business_id_fkey";

alter table "public"."business_appointment_profiles" add constraint "business_appointment_profiles_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."business_appointment_profiles" validate constraint "business_appointment_profiles_profile_id_fkey";

alter table "public"."business_appointments" add constraint "business_appointments_business_id_fkey" FOREIGN KEY (business_id) REFERENCES businesses(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."business_appointments" validate constraint "business_appointments_business_id_fkey";

alter table "public"."business_appointments" add constraint "business_appointments_job_id_fkey" FOREIGN KEY (job_id) REFERENCES business_location_jobs(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."business_appointments" validate constraint "business_appointments_job_id_fkey";

alter table "public"."business_appointments" add constraint "business_appointments_location_id_fkey" FOREIGN KEY (location_id) REFERENCES business_locations(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."business_appointments" validate constraint "business_appointments_location_id_fkey";

grant delete on table "public"."business_appointment_profiles" to "anon";

grant insert on table "public"."business_appointment_profiles" to "anon";

grant references on table "public"."business_appointment_profiles" to "anon";

grant select on table "public"."business_appointment_profiles" to "anon";

grant trigger on table "public"."business_appointment_profiles" to "anon";

grant truncate on table "public"."business_appointment_profiles" to "anon";

grant update on table "public"."business_appointment_profiles" to "anon";

grant delete on table "public"."business_appointment_profiles" to "authenticated";

grant insert on table "public"."business_appointment_profiles" to "authenticated";

grant references on table "public"."business_appointment_profiles" to "authenticated";

grant select on table "public"."business_appointment_profiles" to "authenticated";

grant trigger on table "public"."business_appointment_profiles" to "authenticated";

grant truncate on table "public"."business_appointment_profiles" to "authenticated";

grant update on table "public"."business_appointment_profiles" to "authenticated";

grant delete on table "public"."business_appointment_profiles" to "service_role";

grant insert on table "public"."business_appointment_profiles" to "service_role";

grant references on table "public"."business_appointment_profiles" to "service_role";

grant select on table "public"."business_appointment_profiles" to "service_role";

grant trigger on table "public"."business_appointment_profiles" to "service_role";

grant truncate on table "public"."business_appointment_profiles" to "service_role";

grant update on table "public"."business_appointment_profiles" to "service_role";

grant delete on table "public"."business_appointments" to "anon";

grant insert on table "public"."business_appointments" to "anon";

grant references on table "public"."business_appointments" to "anon";

grant select on table "public"."business_appointments" to "anon";

grant trigger on table "public"."business_appointments" to "anon";

grant truncate on table "public"."business_appointments" to "anon";

grant update on table "public"."business_appointments" to "anon";

grant delete on table "public"."business_appointments" to "authenticated";

grant insert on table "public"."business_appointments" to "authenticated";

grant references on table "public"."business_appointments" to "authenticated";

grant select on table "public"."business_appointments" to "authenticated";

grant trigger on table "public"."business_appointments" to "authenticated";

grant truncate on table "public"."business_appointments" to "authenticated";

grant update on table "public"."business_appointments" to "authenticated";

grant delete on table "public"."business_appointments" to "service_role";

grant insert on table "public"."business_appointments" to "service_role";

grant references on table "public"."business_appointments" to "service_role";

grant select on table "public"."business_appointments" to "service_role";

grant trigger on table "public"."business_appointments" to "service_role";

grant truncate on table "public"."business_appointments" to "service_role";

grant update on table "public"."business_appointments" to "service_role";

create policy "Enable all actions for business profiles"
on "public"."business_appointment_profiles"
as permissive
for all
to authenticated
using (has_business_profile(business_id));


create policy "Enable all actions for global admins"
on "public"."business_appointment_profiles"
as permissive
for all
to authenticated
using (is_global_admin());


create policy "Enable all actions for business profiles"
on "public"."business_appointments"
as permissive
for all
to authenticated
using (has_business_profile(business_id));


create policy "Enable all actions for global admins"
on "public"."business_appointments"
as permissive
for all
to authenticated
using (is_global_admin());



