create type "public"."custom_field_models" as enum ('leads', 'jobs');

create type "public"."custom_field_types" as enum ('text', 'date', 'number', 'select');

create type "public"."lead_sources" as enum ('website-form', 'phone', 'email', 'referral', 'other');

create type "public"."lead_statuses" as enum ('new', 'qualified', 'nurturing', 'follow-up', 'lost', 'inactive');

create table "public"."custom_fields" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "label" text not null,
    "model" custom_field_models not null,
    "type" custom_field_types not null
);


alter table "public"."custom_fields" enable row level security;

create table "public"."leads" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "creator_id" uuid not null,
    "budget" bigint,
    "customer_id" uuid,
    "status" lead_statuses not null default 'new'::lead_statuses,
    "source" lead_sources not null default 'other'::lead_sources,
    "score" smallint not null default '1'::smallint,
    "custom_fields" jsonb
);


alter table "public"."leads" enable row level security;

CREATE UNIQUE INDEX custom_fields_pkey ON public.custom_fields USING btree (id);

CREATE UNIQUE INDEX leads_pkey ON public.leads USING btree (id);

alter table "public"."custom_fields" add constraint "custom_fields_pkey" PRIMARY KEY using index "custom_fields_pkey";

alter table "public"."leads" add constraint "leads_pkey" PRIMARY KEY using index "leads_pkey";

alter table "public"."leads" add constraint "leads_customer_profile_id_fkey" FOREIGN KEY (customer_id) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."leads" validate constraint "leads_customer_profile_id_fkey";

alter table "public"."leads" add constraint "leads_profile_id_fkey" FOREIGN KEY (creator_id) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."leads" validate constraint "leads_profile_id_fkey";

grant delete on table "public"."custom_fields" to "anon";

grant insert on table "public"."custom_fields" to "anon";

grant references on table "public"."custom_fields" to "anon";

grant select on table "public"."custom_fields" to "anon";

grant trigger on table "public"."custom_fields" to "anon";

grant truncate on table "public"."custom_fields" to "anon";

grant update on table "public"."custom_fields" to "anon";

grant delete on table "public"."custom_fields" to "authenticated";

grant insert on table "public"."custom_fields" to "authenticated";

grant references on table "public"."custom_fields" to "authenticated";

grant select on table "public"."custom_fields" to "authenticated";

grant trigger on table "public"."custom_fields" to "authenticated";

grant truncate on table "public"."custom_fields" to "authenticated";

grant update on table "public"."custom_fields" to "authenticated";

grant delete on table "public"."custom_fields" to "service_role";

grant insert on table "public"."custom_fields" to "service_role";

grant references on table "public"."custom_fields" to "service_role";

grant select on table "public"."custom_fields" to "service_role";

grant trigger on table "public"."custom_fields" to "service_role";

grant truncate on table "public"."custom_fields" to "service_role";

grant update on table "public"."custom_fields" to "service_role";

grant delete on table "public"."leads" to "anon";

grant insert on table "public"."leads" to "anon";

grant references on table "public"."leads" to "anon";

grant select on table "public"."leads" to "anon";

grant trigger on table "public"."leads" to "anon";

grant truncate on table "public"."leads" to "anon";

grant update on table "public"."leads" to "anon";

grant delete on table "public"."leads" to "authenticated";

grant insert on table "public"."leads" to "authenticated";

grant references on table "public"."leads" to "authenticated";

grant select on table "public"."leads" to "authenticated";

grant trigger on table "public"."leads" to "authenticated";

grant truncate on table "public"."leads" to "authenticated";

grant update on table "public"."leads" to "authenticated";

grant delete on table "public"."leads" to "service_role";

grant insert on table "public"."leads" to "service_role";

grant references on table "public"."leads" to "service_role";

grant select on table "public"."leads" to "service_role";

grant trigger on table "public"."leads" to "service_role";

grant truncate on table "public"."leads" to "service_role";

grant update on table "public"."leads" to "service_role";


