alter table "public"."business_location_profiles" drop constraint "location_profiles_pkey";

drop index if exists "public"."location_profiles_pkey";

create table "public"."business_tokens" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "business_id" uuid not null,
    "token_type" text not null,
    "token" text not null,
    "service" text not null
);


alter table "public"."business_tokens" enable row level security;

alter table "public"."business_location_profiles" add column "referrer_profile_id" uuid;

CREATE UNIQUE INDEX business_location_profiles_pkey ON public.business_location_profiles USING btree (location_id, profile_id);

CREATE UNIQUE INDEX business_tokens_pkey ON public.business_tokens USING btree (id);

alter table "public"."business_location_profiles" add constraint "business_location_profiles_pkey" PRIMARY KEY using index "business_location_profiles_pkey";

alter table "public"."business_tokens" add constraint "business_tokens_pkey" PRIMARY KEY using index "business_tokens_pkey";

alter table "public"."business_location_profiles" add constraint "business_location_profiles_referrer_profile_id_fkey" FOREIGN KEY (referrer_profile_id) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."business_location_profiles" validate constraint "business_location_profiles_referrer_profile_id_fkey";

alter table "public"."business_tokens" add constraint "business_tokens_business_id_fkey" FOREIGN KEY (business_id) REFERENCES businesses(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."business_tokens" validate constraint "business_tokens_business_id_fkey";

grant delete on table "public"."business_tokens" to "anon";

grant insert on table "public"."business_tokens" to "anon";

grant references on table "public"."business_tokens" to "anon";

grant select on table "public"."business_tokens" to "anon";

grant trigger on table "public"."business_tokens" to "anon";

grant truncate on table "public"."business_tokens" to "anon";

grant update on table "public"."business_tokens" to "anon";

grant delete on table "public"."business_tokens" to "authenticated";

grant insert on table "public"."business_tokens" to "authenticated";

grant references on table "public"."business_tokens" to "authenticated";

grant select on table "public"."business_tokens" to "authenticated";

grant trigger on table "public"."business_tokens" to "authenticated";

grant truncate on table "public"."business_tokens" to "authenticated";

grant update on table "public"."business_tokens" to "authenticated";

grant delete on table "public"."business_tokens" to "service_role";

grant insert on table "public"."business_tokens" to "service_role";

grant references on table "public"."business_tokens" to "service_role";

grant select on table "public"."business_tokens" to "service_role";

grant trigger on table "public"."business_tokens" to "service_role";

grant truncate on table "public"."business_tokens" to "service_role";

grant update on table "public"."business_tokens" to "service_role";


