create table "public"."business_location_customers" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "business_id" uuid not null,
    "location_id" bigint not null,
    "full_name" text not null,
    "email" text not null,
    "phone" text
);


alter table "public"."business_location_customers" enable row level security;

CREATE UNIQUE INDEX business_location_customers_pkey ON public.business_location_customers USING btree (id);

alter table "public"."business_location_customers" add constraint "business_location_customers_pkey" PRIMARY KEY using index "business_location_customers_pkey";

alter table "public"."business_location_customers" add constraint "business_location_customers_business_id_fkey" FOREIGN KEY (business_id) REFERENCES businesses(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."business_location_customers" validate constraint "business_location_customers_business_id_fkey";

alter table "public"."business_location_customers" add constraint "business_location_customers_location_id_fkey" FOREIGN KEY (location_id) REFERENCES business_locations(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."business_location_customers" validate constraint "business_location_customers_location_id_fkey";

grant delete on table "public"."business_location_customers" to "anon";

grant insert on table "public"."business_location_customers" to "anon";

grant references on table "public"."business_location_customers" to "anon";

grant select on table "public"."business_location_customers" to "anon";

grant trigger on table "public"."business_location_customers" to "anon";

grant truncate on table "public"."business_location_customers" to "anon";

grant update on table "public"."business_location_customers" to "anon";

grant delete on table "public"."business_location_customers" to "authenticated";

grant insert on table "public"."business_location_customers" to "authenticated";

grant references on table "public"."business_location_customers" to "authenticated";

grant select on table "public"."business_location_customers" to "authenticated";

grant trigger on table "public"."business_location_customers" to "authenticated";

grant truncate on table "public"."business_location_customers" to "authenticated";

grant update on table "public"."business_location_customers" to "authenticated";

grant delete on table "public"."business_location_customers" to "service_role";

grant insert on table "public"."business_location_customers" to "service_role";

grant references on table "public"."business_location_customers" to "service_role";

grant select on table "public"."business_location_customers" to "service_role";

grant trigger on table "public"."business_location_customers" to "service_role";

grant truncate on table "public"."business_location_customers" to "service_role";

grant update on table "public"."business_location_customers" to "service_role";

create policy "Enable all actions for business admins"
on "public"."business_location_customers"
as permissive
for all
to authenticated
using (business_profile_has_role(business_id, 'admin'::text));


create policy "Enable all actions for business manager"
on "public"."business_location_customers"
as permissive
for all
to authenticated
using (business_profile_has_role(business_id, 'manager'::text));


create policy "Enable all actions for global admins"
on "public"."business_location_customers"
as permissive
for all
to authenticated
using (is_global_admin());


create policy "Enable all actions for location admin"
on "public"."business_location_customers"
as permissive
for all
to authenticated
using (location_profile_has_role(location_id, 'admin'::text));


create policy "Enable all actions for location managers"
on "public"."business_location_customers"
as permissive
for all
to authenticated
using (location_profile_has_role(location_id, 'manager'::text));


create policy "Enable all for location employees"
on "public"."business_location_customers"
as permissive
for all
to authenticated
using (has_location_profile(location_id));



